version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: cpr-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: gtacpr
      POSTGRES_DB: cpr_may18
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    name: cpr-postgres-data 