apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"
      queryTimeout: "60s"
      httpMethod: "GET"
      manageAlerts: true
      alertmanagerUid: "alertmanager"
      prometheusType: "Prometheus"
      prometheusVersion: "2.47.0"
      cacheLevel: "High"
      incrementalQuerying: true
      incrementalQueryOverlapWindow: "10m"
      disableRecordingRules: false
    secureJsonData: {}
    uid: "prometheus"
    version: 1

  - name: AlertManager
    type: alertmanager
    access: proxy
    url: http://alertmanager:9093
    uid: "alertmanager"
    jsonData:
      implementation: "prometheus"
      handleGrafanaManagedAlerts: false
    version: 1 